---
title: "Solution - Assignment 3"
author: "Visualizations"
date: "Deadline: Monday 20-03-2023, 17.00"
output: 
html_document:
self_contained: false
lib_dir: libs
---

```{r echo=FALSE}
knitr::opts_chunk$set(
  echo    = TRUE,
  eval    = FALSE
)
```

---

### Introduction
In this assignment you have practiced with visualizations using ggplot. We have taken a step back from the trade data, but now you should be able to apply this to any data you have as well..

---

1. **Before being able to do this assignment, we will need to go through some lecture material. We start by going through the lecture "Recap Lecture ggplot", which can be found on the website under: After the training trade - Material to use - Additional lectures + practicals. I will present this lecture in our weekly R session in the week of 27-02 till 03-03. If you are not there, or if you already want to start, go through this lecture yourself.**

*Bonus: Try to run some of the code from these slides yourself, such that you see if you can recreate the figures.*

We went through the slides together, and hopefully you understand most of these 'recap' slides. If you have any questions, please reach out to me.

---

2. **If you have been through these slides, you should not be able to do "Practical ggplot - 2", which is on the website under: After the training trade - Material to use - Additional lectures + practicals. There are already hints and solutions in that document. Try to do the exercises yourself first, use the hint, and only afterwards look at the solutions.**

*Hint: Work together with your colleagues to understand this practical.*

The solutions of this practical can already be found in the "Practical ggplot - 2" file by clicking on the "solution" buttons. 

---

3. **If you were successful in understanding the "Recap Lecture ggplot" lecture, and if you managed to solve the practical, it is now time to go to a more extensive lecture. Please go through the "Lecture Data Visualization", which is on the website under: After the training trade - Material to use - Additional lectures + practicals. Try to go through the slides yourself and to understand them. I might be able to present a part of it, but that depends a bit on our schedule in the meetings. Thus, try to go through the lecture slides yourself and learn more about ggplot. There is quite some repetition from the previous lecture, to hopefully help you understand it even better.**

You should have gone through these slides yourself. There are many slides, but it should give you a good impression of the things you can do with ggplot. If you want to make a new figure, it can be useful to open these slides again and see what kind of figure you would like to create and then to adjust the code found in the slides to make such a figure. Again, please let me know if there are any remaining questions.

---

4. **Along with this set of slides, there is a practical as well. This is the "Practical ggplot - 1" practical, which is on the website under: After the training trade - Material to use - Additional lectures + practicals. This is an R Markdown file which you should download, and you can just make the exercises in that document. This practical accompanies the lecture, so go through the lecture slides again, while simultaneously making the practical**

The solutions of this practical can be found under "Additional lectures + practicals" with the title "Solutions - Practical ggplot - 1".

---

BONUS: **Now you have learned a lot about visualizations using ggplot! I hope this makes you excited to start making your own visualizations as well. As a bonus exercise, you can therefore try to use any data you have, load it into R, and make a nice visualization of it. Be creative, and really think about what would be interesting to visualize!! :)**

We have worked on this together in the class on Wednesday March 15. Remember the importance of understanding your data, thinking about the type of figure you want to make (make a sketch on paper!!), getting your data in the right format, and only then creating the figure! We will continue to practice with this.

---

End of Assignment

You have now learned a lot about visualizations! You are able to create many beautiful figures, which will be extremely useful for both understanding your data, as well as to present it to others.

---