---
title: "Solution - Assignment 2"
author: "Analyzing ICUMS data - 1"
date: "Deadline: Monday 27-02-2023, 17.00"
output: 
html_document:
self_contained: false
lib_dir: libs
---

```{r echo=FALSE}
knitr::opts_chunk$set(
  echo    = TRUE,
  eval    = FALSE
)

```

---

### Introduction
In this assignment you used raw ICUMS data to check the data for outliers, and to make some visualizations.

There are (again, sorry!) no clear cut answers to these exercises. This assignment was really aimed at your understanding of the Trade data and how to use it in writing code, checking for strange observations, and creating visualizations. So these solutions will not be that helpful, please reach out to me if you have any further questions.

---

1. **Create a new folder in your Trade R folder, called total, and in the folder total, add a folder input and a folder output. Now download the Trade vulnerability ICUMS.R file and put it in the Trade R folder, if you already had this one in your folder, please delete the old one and download it again from the website (I made some changes). Then ask Femke for the data you need for this assignment, she will give it to you using a USB, this is necessary to be able to do this assignment.**

I have already checked this for most of you, if you are unsure if you did this correctly, please let me check it on your computer (or ask your colleagues to check it for you).

---

2. **In this assignment we are looking at the Trade vulnerability ICUMS code, and focusing on 2022. Open the R script Trade vulnerability ICUMS code.R, and look at the part: # Read 2022 Icums data - OR LOAD DATA DIRECTLY FROM R WORKSPACE!!!, under 2022. IMPORTANT NOTE: you can NOT run this part of the code yourself, as you do NOT have the raw ICUMS data on your computer in your Trade R folder. Just go through this part of the code, and try to understand a bit of what happens there. It is okay to not fully understand every part of it, as we will discuss this together, but at least look at it and try t guess what might happen in the code. What is the input? What is the output?**

Try to be able to explain what happens to someone else, if you are succesful in that, you have understood the code. We can discuss this together.

---

3. **Now go to line 284: # ALTERNATIVE = READ RAW FROM WORKSPACE!. Run the load command in this code chunk. This allows you to read the raw data into your environment directly.**

You will probably have been successful in doing this if you managed to proceed with the assignment. Do you understand what happens here and which data you are loading into R at this point?

---

4. **Try to understand the code under: # Rename columns and select, same format for every type of input. This means line 189 until 376. Also run this code to create the clean versions of the raw data.**

*Hint: This looks like a lot of code, but actually a very similar thing is done separately for import, re-import, warehousing, regime 9, export, and re-export. Just some mutating, renaming, and selecting.*

I cannot check this, please reach out to me if you had any issues with this.

---

5. **If you have ran this code up to line 376, you see another chunk of code, again labelled: # ALTERNATIVE = READ CLEAN FROM WORKSPACE!, at line 377. Instead of running the code like we just did, we could have also just started by running line 379, and we would have gotten the same data in our environment. That is, because I just saved my environment after running the code up to line 376 as raw_icums_22_clean.RData, and gave that to you. Try for yourself to see if indeed running the code up to 376 gives you the same objects in your environment as cleaning your environment and then running line 379.**

Again, I cannot check this, please reach out to me if you had any issues with this.

---

6. **The data you have in your environment now is the raw ICUMS data for 2022, but cleaned up a bit by renaming columns, adding some additional columns, and deleting some columns. This can be used to check for outliers. This is done in the code under: # First sanity checks, line 382-849. Again, a very similar code is just repeated for import, re-import, warehousing, regime 9, export, and re-export. Let us focus on imports, line 384-437. Run lines 386-421, and understand what happens there.**

Again, I cannot check this, please reach out to me if you had any issues with this.

**What is `yearly_sum_imp` showing? What is `monthly_sum_imp` showing? And what are `top10_cif_month_import` and `cif_0_import`?**

`yearly_sum_imp` shows the sum of the CIF values for imports in 2022, `monthly_sum_imp` shows the sum of the CIF values for imports in 2022 per month. `top10_cif_month_import` shows the 10 highest CIF values for every month of 2022, this is used to check for outliers. `cif_0_import` shows all CIF values of zero in 2022, a zero value should not be possible, so it is strange to find that in the data, which is why we want to check for which products we see this happening.

---

7. **Run the code under # Make plot. This creates a plot called `imp_top10_plot`, run that plot and see what it looks like. What do you think it shows?**

**To really understand how to make plots, you need more information about data visualization. We will spend time on this together, but if you have time left, you can already try to go through the lectures and practicals supplied under "Additional lectures + practicals" on the after the training: trade page. This is if you want to improve your visualization skills in R yourself. If you spend time on this and have questions, feel free to reach out to me. (But I do think it would be best if we spend more time on R together that I can just go through these lectures with all of you together as well)**

This plot shows the 10 highest CIF values for imports in 2022 per month, it is useful to make this figure to check for any outliers.

---

8. **What you have ran for imports can also be done for the other types of trade data we have, so try to run all checks under # First sanity checks. Now you can also run the code under:   ### Save checks into Excel - top 10 per month ###, and   ### Save checks into Excel - zero cif and fob values ###, to save these checks into Excel sheets. Run this code and check whether it was successful.**

You can check this yourself by checking if you indeed have such an Excel file, and by checking what it looks like.

---

9. **Finally, you can run the code under: # Remove outliers from data --> for now best option, need to consult with ICUMS (GhanaLink or customs?) # And make monthly datasets, line 852-1012. Run this code and try to understand what happens.**

This part of the code drops any CIF values above 300,000,000 GH₵, such that we can make visualization without taking extreme outliers into consideration. This is of course not how we should treat our data, we should consult customs and ask whether these very high values are actually true, or whether there has been mistakes in the data and if they can adjust them to improve the quality of the data.

---

End of Assignment

This was a difficult assignment, as it requires you to read and understand quite a lot of code. Try to keep on looking at this code over the next weeks, and to run parts of it again, to really make sure you understand what happens.

As soon as we have new ICUMS templates, we will alter the code such that we will have a final document in which we can analyse our trade data, make important visualizations, and which we can also use for data requests. We will (hopefully!) be able to do this together / you will do it and I will sit back and relax :). But that does really require you to really understand this code! Hence, do really reach out to me if anything is still unclear, or if we need to discuss parts of the code.

---
