---
title: "Practical D"
author: "Statistical Programming in R"
date: ""
output: 
html_document:
self_contained: false
lib_dir: libs
---


```{r echo=FALSE}
knitr::opts_chunk$set(
  echo    = TRUE,
  eval    = FALSE
)

```

---

#### Exercises
In this practical we are going to use sample trade data to practice with analysing and summarising data. This builds on the work you have done in Practical C.

---

1. **Open the workspace icums_22_sample.RData. You need to download this file and put it in the project folder.**


---

2. **Inspect the data, what does this data set show? What can this data be used for?**

---

3. **Select a specific subset of the data, for example only the columns: tradeflow, month_name, hs_code, and cif.**

---

4. **Now repeat question 3, but use a different method to do it. Which method do you think is better to use, and why? Bonus: would you be able to find a third method to do this? **

---

5. **Select only the columns in which the values are numeric.**

---

6. **Get more information on the data by creating a table of how many observations there are for each month.**

---

7. **Use the function "aggregate" to find the average imports for every month.**

---


8. **Repeat question 7, now using a pipe.**

---


9. **Add a new column "quarter" which shows which quarter of the year every observation is from.**

---

10. **Load the new dataframe hs_codes.RData into R, and merge this to the icums_22_sample data. Carefully decide on which method you use for this.**

---

11. **If you have time left, try to see what other interesting insights you can create using this data. (Or look at the CPI data again and see if you can apply what we learned this afternoon to the CPI data).**

---

End of Practical

---