## GETTING DATA INTO DESIRED FORMAT

### Setting paths

```{r}
input_data_path <- "regime_9/input/12.Import Data Report (41)DECEMBER 2022_REGIME 9.xlsx"

output_data_path <-"regime_9/output/output_Regime9_December_2022.xls"
```

### Loading Required R Packages

```{r, message=FALSE, warning=FALSE}
library(readxl)    
library(tidyverse)
library(lubridate)
library(janitor)
library(writexl)
library(ggplot2)
library(hrbrthemes)
library(plotly)
library(openxlsx)
# Need to do this do NOT have scientific notation
options(scipen = 10)
```

### Function to Read all Excel Sheets into R

```{r}
# Create the function to read multiple files
multiplesheets <- function(fname) {
   
#### getting info about all excel sheets and reading them into R
  sheets <- readxl::excel_sheets(fname)
  
  data <- lapply(sheets, function(x){
    readxl::read_excel(fname, sheet = x, col_names = TRUE, skip = 5) 
  }
  )
  
### Appending the Data Files into a Single Data Frame
df_data <- data.table::rbindlist(data)

#### print data frame
return(df_data)

}

```
  

### Applying the Function on the Excel Data

```{r}

df_data_raw <- multiplesheets(input_data_path)

```

### Getting the data in right format

```{r}
# Create new clean data frame
df_data_clean_copy <- df_data_raw

# Change dataframe to clean version
df_data_clean <- df_data_clean_copy %>%
  mutate(
    # Add day, month, year
    DAY = format(BOE_DECLARATION_DATE, format = "%d"),
    MONTH = format(BOE_DECLARATION_DATE, format = "%m"),
    YEAR = format(BOE_DECLARATION_DATE, format = "%Y"),
    HEAD_CUST_OFF_CODE = NA,
    HEAD_DECLARANT_ID = NA,
    HEAD_MODE_TRANS_CODE = NA,
    HEAD_CTRY_NAT_VESSEL = NA,
    ITEMS_NET_MASS = NA) %>%
  # Arrange by year, month, day
  arrange(YEAR, MONTH, DAY) %>% 
  # Getting columns in required order, and selecting which ones we want
  select(DAY, MONTH, YEAR, HEAD_CUST_OFF_CODE, BOE_NO, ITEM_NUMBER,	
         HEAD_DECLARANT_ID, IMPORTER_TIN, HEAD_MODE_TRANS_CODE, 
         HEAD_CTRY_NAT_VESSEL, ITEM_CPC, ITEM_HS_CODE, 
         COUNTRY_OF_ORIGIN, ITEMS_NET_MASS, ITEM_GROSS_WEIGHT_KG, ITEM_QUANTITY, 
         COUNTRY_OF_CONSIGNMENT, ITEM_CIF_GHS, ITEM_INSURANCE_GHS, 
         ITEM_FREIGHT_GHS) %>%
  # Change column names
  rename(CUSTOM = HEAD_CUST_OFF_CODE, 
         DECNUM = BOE_NO, 
         ITEMNUM = ITEM_NUMBER, 
         AGENT = HEAD_DECLARANT_ID, 
         TRADER = IMPORTER_TIN, 
         MOT = HEAD_MODE_TRANS_CODE,
         NATIONALITY = HEAD_CTRY_NAT_VESSEL, 
         CPC = ITEM_CPC, 
         PRODUCT = ITEM_HS_CODE, 
         PARTNER = COUNTRY_OF_ORIGIN, 
         NETWEIGHT = ITEMS_NET_MASS, 
         GROSSWEIGHT = ITEM_GROSS_WEIGHT_KG, 
         QUANTITY = ITEM_QUANTITY, 
         "COUNTRYF/L" = COUNTRY_OF_CONSIGNMENT, 
         CUSTOMVALUE = ITEM_CIF_GHS, 
         INSURANCE = ITEM_INSURANCE_GHS, 
         FREIGHT = ITEM_FREIGHT_GHS)

```

### Subsetting data into data frames of not more than 45,000 rows and assigning them to workbook sheets

```{r}
# Define maximum number of rows per sheet
max_rows <- 45000

# Make new column which specifies the row category, so which sheet it should be on
df_data_clean <- df_data_clean %>% 
  mutate(row_cat = row_number(),
         row_cat = cut(row_cat, 
                       breaks = c(0, max_rows*c(1:ceiling(nrow(df_data_clean)/max_rows))))
  )

# Now split the data based on this row category
output <- split(df_data_clean, df_data_clean$row_cat)

# Rename the sheets of the output file to 1 until the final number of sheets
names(output) <- c(1:length(output))

# Drop the row_cat column in every item in the list
output_final <- lapply(output, function(x){x[,1:(ncol(x)-1)]})

```

### Exporting the data to Excel

```{r}
# Save to excel
write_xlsx(output_final, output_data_path)

```
