---
title: "GSS Export Data Formating and Quality Checks"
author: "GSS Data Science Unit"
date: "2022-11-08"
output: html_document
---

## 1.0 GETTING DATA INTO DESIRED FORMAT

### Setting paths

```{r}
input_data_path <- "Data/Test data/ICUMS DATA_2020/01. Merchandised Export (10)_SEPT 2020.xlsx"

ouput_data_path <-"Output/Exports/output_Merchandised_Exports_September_2020.xlsx"
```

### Loading Required R Packaged

```{r, message=FALSE, warning=FALSE, echo=FALSE}

library(readxl)    
library(tidyverse)
library(dplyr)
library(lubridate)
library(janitor)
library(writexl)
library(ggplot2)
library(hrbrthemes)
library(plotly)
library(openxlsx)
library(vctrs)
# Need to do this do NOT have scientific notation
options(scipen = 10)

```

### Function to Read all Excel Sheets into R

```{r}

multiplesheets <- function(fname) {
   
#### getting info about all excel sheets and reading them into R
  sheets <- readxl::excel_sheets(fname)
  data <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x, col_names = TRUE, skip = 4) %>% 
                   # Sheet 13 has an additional row, drop it here
      filter(HEAD_CUST_OFF_CODE != "CUSTOM OFFICE") %>%
            # Changed as.POSIXct to  convert to date, to also properly read sheet 13
    mutate(HEAD_TIME_PROC = convert_to_date(HEAD_TIME_PROC, character_fun = lubridate::dmy)))
  
  data_frame <- lapply(data, as.data.frame)

#### assigning names to data frames
names(data_frame) <- sheets

### Appending the Data Files into a Single Data Frame
df_data <- data.table::rbindlist(data_frame)

#### print data frame
return(df_data)

}

```
  

### Applying the Function on the Excel Data
```{r}

df_data <- multiplesheets(input_data_path)

```

### Getting the data in right format

```{r}

# Creating columns for day, month and year based on the HEAD_TIME_PROC column
df_data$DAY <- format(df_data$HEAD_TIME_PROC, format = "%d")
df_data$MONTH <- format(df_data$HEAD_TIME_PROC, format = "%m")
df_data$YEAR <- format(df_data$HEAD_TIME_PROC, format = "%Y")

# Create label of which month, assuming that all data is from the same month
which_month <- month.name[as.numeric(df_data$MONTH[1])]
# also create a capitalised month label
WHICH_MONTH <- toupper(which_month)

# Creating an empty column (Column U in excel)
df_data$COLUMN_U <- NA

# removing the HEAD_TIME_PROC column
df_data <- df_data %>% 
  arrange(YEAR, MONTH, DAY) %>% 
  select(-HEAD_TIME_PROC)

# Getting columns in required order
df_data <- df_data %>% 
  select(DAY, MONTH, YEAR, HEAD_CUST_OFF_CODE, HEAD_DECL_NO, ITEMS_NO,	
         HEAD_DECLARANT_ID, HEAD_EXPORTER_CODE, HEAD_MODE_TRANS_CODE, 
         HEAD_CTRY_NAT_VESSEL, ITEMS_CPC_CODE, ITEMS_HS_CODE, 
         HEAD_COUNTRY_ORIG_DEST, ITEMS_NET_MASS, ITEMS_GROSS_MASS, ITEMS_QTY, 
         COUNTRY_OF_CONSIGNMENT, ITEMS_FOB_GHC, ITEMS_INSURE_GHC, 
         ITEMS_FREIGHT_GHC, COLUMN_U, ITEMS_CIF_GHC, ITEMS_SUPPLEMENTARY1, 
         ITEMS_GOODS_DESC, HEAD_DECLARANT_NAME, HEAD_DECLARANT_ADDRESS, 
         HEAD_EXPORTER_NAME, HEAD_EXPORTER_ADDRESS)

# Creating a vector of initial column names, includes "del" for cells that need to be empty later
colnames_1 <- c("head_time_proc", "del_1", "del_2", "head_cust_off_code", 
                "head_decl_no", "items_no",	"head_declarant_id", 
                "head_exporter_code", "head_mode_trans_code", 
                "head_ctry_nat_vessel", "items_cpc_code", "items_hs_code", 
                "head_country_orig_dest", "items_net_mass", "items_gross_mass", 
                "items_qty", "country_of_consignment", "items_fob_ghc", 
                "items_insure_ghc", "items_freight_ghc", "del_3", 
                "items_cif_ghc", "items_supplementary1", "items_goods_desc", 
                "head_declarant_name", "head_declarant_address", 
                "head_exporter_name", "head_exporter_address")

colnames(df_data) <- colnames_1

```

### Creating columns sub-titles

```{r}
sub_title_new <- c("DAY", "MONTH", "YEAR", "CUSTOM", "DECNUM", 
                   "ITEMNUM", "AGENT", "TRADER", "MOT",
                   "NATIONALITY", "CPC", "PRODUCT", "PARTNER", 
                   "NETWEIGHT", "GROSSWEIGHT", "QUANTITY", 
                   "COUNTRYF/L", "CUSTOMVALUE", "INSURANCE", 
                   "FREIGHT","EMPTY", "ITEMS_CIF_GHC",
                   "ITEMS_SUPPLEMENTARY1", 
                   "ITEMS_GOODS_DESC", "HEAD_DECLARANT_NAME", 
                   "HEAD_DECLARANT_ADDRESS", "HEAD_EXPORTER_NAME", 
                   "HEAD_EXPORTER_ADDRESS")

colnames(df_data) <- sub_title_new

```

### Subsetting data into data frames of not more than 45,000 rows and assigning them to workbook sheets
```{r}

x=45000
df_data <- df_data %>% 
  mutate(row_cat = row_number())

df_data$row_cat <- cut(df_data$row_cat, 
                       breaks = c(1, x*c(1:ceiling((nrow(df_data)/x)), Inf)), 
                       labels = NULL)

output <- split(df_data, df_data$row_cat)

empty_tabs <- rep(TRUE, length(output))
# Loop over list
for(i in 1:length(output)){
  output[[i]] <- output[[i]] %>%
    select(-row_cat) 
  if(nrow(output[[i]])==0){
    empty_tabs[i] <- FALSE
  }
}
output <- output[empty_tabs]

# for (i in 1:length(output)) {
#   names(output[i]) <- paste("Data", i, sep = " ")
# }

wb <- createWorkbook()

for (i in 1:length(output)) {
  addWorksheet(wb, sheetName = names(output[i]))
  writeData(wb, sheet = names(output[i]), x = output[[i]])
}

saveWorkbook(wb, ouput_data_path, overwrite = TRUE)
```

