---
title: "GSS Export Data Formating and Quality Checks"
author: "GSS Data Science Unit"
date: "2023-02-01"
output: html_document
---

## GETTING DATA INTO DESIRED FORMAT

### Setting paths

```{r}
input_data_path <- "export/input/01. Merchandised Export (10)_DEC.xlsx"

ouput_data_path <-"export/output/output_Merchandised_Exports_December_2022.xlsx"
```

### Loading Required R Packages

```{r, message=FALSE, warning=FALSE, echo=FALSE}

library(readxl)    
library(tidyverse)
library(lubridate)
library(janitor)
library(writexl)
library(ggplot2)
library(hrbrthemes)
library(plotly)
library(openxlsx)
# Need to do this do NOT have scientific notation
options(scipen = 10)

```

### Function to Read all Excel Sheets into R

```{r}
# Create the function to read multiple files
multiplesheets <- function(fname) {
   
#### getting info about all excel sheets and reading them into R
  sheets <- readxl::excel_sheets(fname)
  
  data <- lapply(sheets, function(x){
    readxl::read_excel(fname, sheet = x, col_names = TRUE, skip = 4) %>% 
      # One of the ICUMS files has an extra row, drop it here --> should not be necessary
      filter(HEAD_CUST_OFF_CODE != "CUSTOM OFFICE") %>%
      # Change the date to read as date variable
      mutate(HEAD_TIME_PROC = convert_to_date(HEAD_TIME_PROC, character_fun = lubridate::dmy))
  }
  )
  
  # Change the list to a dataframe
  data_frame <- lapply(data, as.data.frame)

#### assigning names to data frames
names(data_frame) <- sheets

### Appending the Data Files into a Single Data Frame
df_data <- data.table::rbindlist(data_frame)

#### print data frame
return(df_data)

}

```
  

### Applying the Function on the Excel Data

```{r}
# Read all the sheets of the input data
df_data_raw <- multiplesheets(input_data_path)

```

### Getting the data in right format

```{r}
# Create new clean data frame
df_data_clean <- df_data_raw

# Creating columns for day, month and year based on the HEAD_TIME_PROC column
df_data_clean$DAY <- format(df_data_clean$HEAD_TIME_PROC, format = "%d")
df_data_clean$MONTH <- format(df_data_clean$HEAD_TIME_PROC, format = "%m")
df_data_clean$YEAR <- format(df_data_clean$HEAD_TIME_PROC, format = "%Y")

# Creating an empty column (Column U in excel)
df_data_clean$COLUMN_U <- NA

# removing the HEAD_TIME_PROC column, and arrange by year, month, day
df_data_clean <- df_data_clean %>% 
  arrange(YEAR, MONTH, DAY) %>% 
  select(-HEAD_TIME_PROC)

# Getting columns in required order
df_data_clean <- df_data_clean %>% 
  select(DAY, MONTH, YEAR, HEAD_CUST_OFF_CODE, HEAD_DECL_NO, ITEMS_NO,	
         HEAD_DECLARANT_ID, HEAD_EXPORTER_CODE, HEAD_MODE_TRANS_CODE, 
         HEAD_CTRY_NAT_VESSEL, ITEMS_CPC_CODE, ITEMS_HS_CODE, 
         HEAD_COUNTRY_ORIG_DEST, ITEMS_NET_MASS, ITEMS_GROSS_MASS, ITEMS_QTY, 
         COUNTRY_OF_CONSIGNMENT, ITEMS_FOB_GHC, ITEMS_INSURE_GHC, 
         ITEMS_FREIGHT_GHC, COLUMN_U, ITEMS_CIF_GHC, ITEMS_SUPPLEMENTARY1, 
         ITEMS_GOODS_DESC, HEAD_DECLARANT_NAME, HEAD_DECLARANT_ADDRESS, 
         HEAD_EXPORTER_NAME, HEAD_EXPORTER_ADDRESS)

```

### Changing the column names

```{r}
# Make vector of new names and change the column names
colnames(df_data_clean) <- c("DAY", "MONTH", "YEAR", "CUSTOM", "DECNUM", 
                             "ITEMNUM", "AGENT", "TRADER", "MOT",
                             "NATIONALITY", "CPC", "PRODUCT", "PARTNER", 
                             "NETWEIGHT", "GROSSWEIGHT", "QUANTITY", 
                             "COUNTRYF/L", "CUSTOMVALUE", "INSURANCE", 
                             "FREIGHT","EMPTY", "ITEMS_CIF_GHC",
                             "ITEMS_SUPPLEMENTARY1", 
                             "ITEMS_GOODS_DESC", "HEAD_DECLARANT_NAME",
                             "HEAD_DECLARANT_ADDRESS", "HEAD_EXPORTER_NAME", 
                             "HEAD_EXPORTER_ADDRESS")

```

### Subsetting data into data frames of not more than 45,000 rows and assigning them to workbook sheets

```{r}
# Define maximum number of rows per sheet
# NOTE: In the final R script this has to be changed to 45000
max_rows <- 10000

# Make new column which specifies the row category, so which sheet it should be on
df_data_clean <- df_data_clean %>% 
  mutate(row_cat = row_number(),
         row_cat = cut(row_cat, 
                       breaks = c(1, max_rows*c(1:ceiling((nrow(df_data_clean)/max_rows)), Inf) + 1), 
                       labels = NULL))

# Now split the data based on this row category
output <- split(df_data_clean, df_data_clean$row_cat)

# Create a vector of TRUE TRUE TRUE to select which sheets should be empty or not
data_in_sheet <- rep(TRUE, length(output))

# Loop over output, to select which sheets are empty (if there are less than the indicated max rows)
for(i in 1:length(output)){ # Loop over the dataframes in the list output
  # If zero rows, change data in sheet to FALSE, as no data in the sheet
  if(nrow(output[[i]])==0){
    data_in_sheet[i] <- FALSE
  }
}

# Only keep the output with data in the sheets
output <- output[data_in_sheet]
```

### Exporting the data to Excel

```{r}
# Create empty workbook
wb <- createWorkbook()

# For every data frame in the output list, create a new worksheet, and write the data to the worksheet
for (i in 1:length(output)) {
  addWorksheet(wb, sheetName = names(output[i]))
  writeData(wb, sheet = names(output[i]), x = output[[i]])
}

# Save data to your output path
saveWorkbook(wb, ouput_data_path, overwrite = TRUE)

```
