---
title: "Practical C"
author: "Statistical Programming in R"
date: ""
output: 
html_document:
self_contained: false
lib_dir: libs
---

```{r echo=FALSE}
knitr::opts_chunk$set(
  echo    = TRUE,
  eval    = FALSE
)

```

---

#### Exercises
In this practical we are going to use sample CPI data to practice with data manipulation.

---

1. **Open the workspace cpi_sample.RData. You need to download this file and put it in the project folder.**

---

2. **Inspect the data, how many rows and columns are there in the data? What does that mean?**

---

3. **Further inspect the data, what does this data set show? What can this data be used for?**

---

4. **In the `cpi_sample` data set, use a pipe and the select function to get prices and quantities from January to March.**

---

5. **Following from question 4,  Use a pipe to generate a new variable `PR_0121_new`, which is twice the old variable `PR_0121`.**

---

6. **Following from question 4, also use the transform function to transform the column `PR_0121` into half of it.**

---

7. **Filter the data for only `Greater Accra` region. Also filter out the missing responses in `outlet_type` variable**

---

8. **Filter the data for prices in January greater than 5**

--- 

9. **Rename `PR_0121` as price_jan_21**

--- 

10. **Arrange the data by PR_0121 **

--- 

11. **Arrange the data by PR_0121 in descending order **

--- 

End of Practical

---
