---
title: "Solution - Assignment 1"
author: "Creating CPI Indices file + visualizations"
date: "Deadline: Monday 27-02-2023, 17.00"
output: 
html_document:
self_contained: false
lib_dir: libs
---

```{r echo=FALSE}
knitr::opts_chunk$set(
  echo    = TRUE,
  eval    = FALSE
)

```

---

### Note to the solutions
In this assignment you created the CPI indices file from the input CPI data. Moreover, this was an assignment to start making your own visualisations. That means that there are no very general solutions, it is mainly you own understanding that should have been tested and improved. Hence, please reach out to me if you have any further issues.

---

1. **We need a folder on our computer for CPI R codes. If you do not have such a folder yet, start with creating a new folder called CPI R (or any similar name you would find useful). Then create a R Project in this folder. All the assignments you will make should have their own new R script which will be saved in this same folder, such that it will be under the same project.**

*It is very important to have this set-up for all future assignments, so if you are unsure about whether you did this correctly, please ask for help!*

This should just be set up in this way on your computer, I can check this for you.

---

---

2. **Download the Excel files sent in the Whatsapp group and save them in your CPI R folder on your computer. Also download the CPI_indices_code_nocomments.R file from the website, it can be found under "After the training: CPI", R scripts. Also put this in your CPI R folder. Now open your CPI R project from your CPI R folder on your computer, and open the CPI_indices_code_nocomments.R file. Before starting on the assignment, make sure you clean your environment.**

Same here, without this you would not have been able to finish the assignment, so I assume you all succeeded in this.

---

3. **Go through the code to create the CPI indices again, and check if you still understand everything. If you have forgotten what a certain part of the code is for, try to find it out again. Use the help function, Google, and trying to run parts of the code yourself. Or ask your colleagues to help you. If you really cannot solve a problem, then feel free to reach out to Femke.**

Again, just based on your own understanding.

---

4. **To confirm that you understand the code, add comments to every part of the code yourself. The comments should be such that it is easy to understand what is going on in the code in every step. If you are able to add comments to the code to describe what happens in every part, you have shown that you really understand the code.**

You should have a document with clear comments above every part of the code now. This should be such that if you look at this code again in a months time, it helps you to understand is. Moreover, it should be clear to your colleagues with a basic understanding of R what happens in the code. Make this a habit in all the code you write as well, to make sure others can understand it more easily.

---

5. **Run the entire code and check whether you indeed get the output file you wanted to create. Check: what should be the output of the code? How and where should it be saved? Can you open the output file and check if that is indeed what it should look like?**

You should have a file called Indices_Jan2021_toNov2022.xlsx (or a similar name) in your CPI R folder now, with the CPI indices up to and including November 2022.

---

6. **If you managed to understand and run the code, you should now have an output document with CPI indices. We are now going to use this to make some visualizations. This is a very open exercise, you should just make two different plots using the CPI output data you created in the previous exercises. Decide for yourself what would be interesting to visualize and try to figure out how to do that.**

*Note: For those who were not present during the visualization lectures, please go to the CPI page on the website, and go through the lectures and practicals yourself to try to learn about visualizations using ggplot in R. If you have questions about this, please reach out to Femke.*

*Hint 1: First create a new R script (called CPI visualizations, or something like that). Start with running the libraries of important packages, then load the data, and then start with your visualizations.*

*Hint 2: Reproduce the visualizations you created during the R training first. Then make new figures to really see if you can apply what you learned.*

*Suggestion: It might be interesting to first calculate the inflation based on the indices, and then make figures on the inflation instead of on the CPI.*

This totally depended on you and what kind of figures you wanted to make! There a many different possibilities.

---

7. **If you managed to create two interesting figures using the data, try to make these figures look better now. Change the theme, change the colours, add a title, change the axis labels etc., such that you create a good looking plot.**

*Hint: Get help from Google!*

Again, this very much depends on what you wanted to make. Please reach out to me if you wanted to change something in your figure but could not figure out how to do that, such that we can do it together!

---

End of Assignment

Please let me know if you have any questions about these solutions.

---
